<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert('INSERT INTO languages (name, code, created_at, updated_at) VALUES 
("Abkhazian", "ab", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"),
("Afar", "aa", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Afrikaans", "af", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Akan", "ak", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Albanian", "sq", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Amharic", "am", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Arabic", "ar", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Aragonese", "an", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Armenian", "hy", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Assamese", "as", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Avaric", "av", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Avestan", "ae", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Aymara", "ay", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Azerbaijani", "az", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Bambara", "bm", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Bashkir", "ba", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Basque", "eu", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Belarusian", "be", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Bengali (Bangla)", "bn", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Bihari", "bh", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Bislama", "bi", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Bosnian", "bs", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Breton", "br", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Bulgarian", "bg", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Burmese", "my", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Catalan", "ca", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Chamorro", "ch", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Chechen", "ce", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Chichewa, Chewa, Nyanja", "ny", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Chinese", "zh", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Chinese (Simplified)", "zh-Hans", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Chinese (Traditional)", "zh-Hant", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Chuvash", "cv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Cornish", "kw", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Corsican", "co", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Cree", "cr", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Croatian", "hr", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Czech", "cs", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Danish", "da", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Divehi, Dhivehi, Maldivian", "dv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Dutch", "nl", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Dzongkha", "dz", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("English", "en", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Esperanto", "eo", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Estonian", "et", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Ewe", "ee", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Faroese", "fo", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Fijian", "fj", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Finnish", "fi", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("French", "fr", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Fula, Fulah, Pulaar, Pular", "ff", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Galician", "gl", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Gaelic (Scottish)", "gd", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Gaelic (Manx)", "gv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Georgian", "ka", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("German", "de", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Greek", "el", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Greenlandic", "kl", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Guarani", "gn", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Gujarati", "gu", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Haitian Creole", "ht", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Hausa", "ha", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Hebrew", "he", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Herero", "hz", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Hindi", "hi", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Hiri Motu", "ho", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Hungarian", "hu", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Icelandic", "is", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Ido", "io", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Igbo", "ig", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Indonesian", "id, in", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Interlingua", "ia", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Interlingue", "ie", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Inuktitut", "iu", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Inupiak", "ik", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Irish", "ga", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Italian", "it", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Japanese", "ja", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Javanese", "jv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kalaallisut, Greenlandic", "kl", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kannada", "kn", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kanuri", "kr", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kashmiri", "ks", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kazakh", "kk", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Khmer", "km", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kikuyu", "ki", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kinyarwanda (Rwanda)", "rw", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kirundi", "rn", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kyrgyz", "ky", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Komi", "kv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kongo", "kg", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Korean", "ko", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kurdish", "ku", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Kwanyama", "kj", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Lao", "lo", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Latin", "la", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Latvian (Lettish)", "lv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Limburgish ( Limburger)", "li", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Lingala", "ln", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Lithuanian", "lt", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Luga-Katanga", "lu", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Luganda, Ganda", "lg", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Luxembourgish", "lb", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Manx", "gv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Macedonian", "mk", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Malagasy", "mg", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Malay", "ms", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Malayalam", "ml", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Maltese", "mt", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Maori", "mi", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Marathi", "mr", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Marshallese", "mh", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Moldavian", "mo", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Mongolian", "mn", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Nauru", "na", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Navajo", "nv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Ndonga", "ng", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Northern Ndebele", "nd", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Nepali", "ne", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Norwegian", "no", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Norwegian bokmål", "nb", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Norwegian nynorsk", "nn", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Nuosu", "ii", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Occitan", "oc", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Ojibwe", "oj", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Old Church Slavonic, Old Bulgarian", "cu", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Oriya", "or", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Oromo (Afaan Oromo)", "om", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Ossetian", "os", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Pāli", "pi", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Pashto, Pushto", "ps", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Persian (Farsi)", "fa", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Polish", "pl", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Portuguese", "pt", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Punjabi (Eastern)", "pa", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Quechua", "qu", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Romansh", "rm", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Romanian", "ro", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Russian", "ru", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Sami", "se", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Samoan", "sm", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Sango", "sg", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Sanskrit", "sa", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Serbian", "sr", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Serbo-Croatian", "sh", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Sesotho", "st", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Setswana", "tn", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Shona", "sn", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Sichuan Yi", "ii", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Sindhi", "sd", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Sinhalese", "si", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Siswati", "ss", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Slovak", "sk", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Slovenian", "sl", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Somali", "so", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Southern Ndebele", "nr", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Spanish", "es", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Sundanese", "su", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Swahili (Kiswahili)", "sw", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Swati", "ss", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Swedish", "sv", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tagalog", "tl", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tahitian", "ty", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tajik", "tg", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tamil", "ta", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tatar", "tt", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Telugu", "te", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Thai", "th", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tibetan", "bo", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tigrinya", "ti", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tonga", "to", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Tsonga", "ts", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Turkish", "tr", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Turkmen", "tk", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Twi", "tw", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Uyghur", "ug", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Ukrainian", "uk", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Urdu", "ur", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Uzbek", "uz", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Venda", "ve", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Vietnamese", "vi", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Volapük", "vo", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Wallon", "wa", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Welsh", "cy", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Wolof", "wo", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Western Frisian", "fy", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Xhosa", "xh", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Yiddish", "yi, ji", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Yoruba", "yo", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Zhuang, Chuang", "za", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '"), 
("Zulu", "zu", "' . Carbon::now()->toDateTimeString() . '", "' . Carbon::now()->toDateTimeString() . '")');
    }
}
